modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/Easy-Sound/issues"

[[mods]]
modId = "easy_sound"
version = "${file.jarVersion}"
displayName = "Easy Sound"
displayURL = "https://curseforge.com/minecraft/mc-mods/easy_sound"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''Description for Example Mod ...'''

[[dependencies.easy_sound]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_sound]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
